// src/components/ui/footer.tsx
import icon from '@/assets/images/icon.png';
import { Github, Instagram, Linkedin } from 'lucide-react';

const linkedin = 'https://www.linkedin.com/company/optifit-software/';
const instagram = 'https://www.instagram.com/optifit.app/';
const github = 'https://github.com/optifit-app';

export const Footer = () => {
  return (
    <div className="flex flex-col gap-4 lg:max-w-screen-2xl mx-auto border border-b-0 py-10 px-25">
      <div className="flex items-center justify-between flex-wrap gap-5 border-b pb-5">
        <div
          className="flex items-center gap-2 select-none cursor-pointer"
          onClick={() => (window.location.href = window.location.origin)}
        >
          <img src={icon} alt="optifit icon" className="h-9 w-9" />
          <span className="text-lg font-semibold">Optifit</span>
        </div>
        <div className="flex items-center gap-5">
          <Linkedin
            className="hover:text-primary cursor-pointer"
            onClick={() => window.open(linkedin)}
          />
          <Instagram
            className="hover:text-primary cursor-pointer"
            onClick={() => window.open(instagram)}
          />
          <Github
            className="hover:text-primary cursor-pointer"
            onClick={() => window.open(github)}
          />
        </div>
      </div>
      <div className="flex items-center justify-between flex-wrap gap-5 border-b pb-5">
        <div className="flex flex-col">
          <h3 className="text-xl font-semibold">Nous contacter</h3>
          <a
            href="mailto:info@optifit.app"
            className="text-[15px] underline text-primary mt-2"
          >
            info@optifit.app
          </a>
          <p className="text-[15px]">
            Avenue du Léman 2<br />
            1005 Lausanne
            <br />
            Suisse
          </p>
        </div>
        <div className="flex flex-col">
          <h3 className="text-xl font-semibold">Liens utiles</h3>
          <a
            href="#pricing"
            className="text-[15px] hover:underline hover:text-primary mt-2"
          >
            Tarifs
          </a>
          <a
            href="#pricing"
            className="text-[15px] hover:underline hover:text-primary"
          >
            Questions fréquentes
          </a>
          <a
            href="/changelog"
            className="text-[15px] hover:underline hover:text-primary"
          >
            Changelog
          </a>
        </div>
        <div className="flex flex-col">
          <h3 className="text-lg font-medium">Besoin d'aide ?</h3>
          <a
            href="mailto:support@optifit.app"
            className="text-[15px]  underline text-primary mt-2"
          >
            support@optifit.app
          </a>
          <a
            href="/terms-and-conditions"
            className="text-[15px] hover:underline hover:text-primary"
          >
            Conditions générales d'utilisations
          </a>
          <a
            href="/privacy-policy"
            className="text-[15px] hover:underline hover:text-primary"
          >
            Politique de confidentialité
          </a>
        </div>
      </div>
      <div className="flex justify-center py-5">
        <span className="text-md font-medium text-muted-foreground">
          © {new Date().getFullYear()} Optifit. Tous droits réservés.
        </span>
      </div>
    </div>
  );
};

// src/components/FooterComponent.vue
<template>
  <footer class="footer">
    <div class="column">
      <div class="brand">
        <img src="../assets/icon.png" alt="logo" height="50px" />
        <div class="text">
          <span class="brand-name">Optifit</span>
          <span class="brand-text">
            &copy; {{ new Date().getFullYear() }} Tous droits réservés.
          </span>
          <span class="swiss-made">
            <img src="../assets/swiss-flag.png" alt="Swiss flag" />
            Swiss made
          </span>
        </div>
      </div>
    </div>
    <div class="column">
      <h2>Liens utiles</h2>
      <div class="links">
        <a href="/#">Accueil</a>
        <a href="/#features">Fonctionnalités</a>
        <a href="https://calendly.com/gabriel-optifit/demo-optifit?hide_gdpr_banner=1&month=2025-04" target="_blank">Je veux une démo</a>
      </div>
    </div>
    <div class="column">
      <h2>Suivez-nous</h2>
      <div class="links">
        <a href="https://www.instagram.com/optifit.app/" target="_blank" class="social-link">
          Instagram
          <i class="pi pi-instagram"></i>
        </a>
        <a
          href="https://www.linkedin.com/company/103099933/admin/dashboard/"
          target="_blank"
          class="social-link"
        >
          Linkedin
          <i class="pi pi-linkedin"></i>
        </a>
        <a href="mailto:info@optifit.app" class="social-link">
          info@optifit.app
          <i class="pi pi-envelope"></i>
        </a>
      </div>
    </div>
  </footer>
</template>

<style scoped lang="scss">
.footer {
  background-color: #ffffff;
  padding: 50px 100px;
  display: flex;
  justify-content: space-between;
  align-items: stretch;
  width: 100%;
  max-width: 1500px;
  border-radius: 20px 20px 0 0;
  border: solid 1px #e0e0e0;
  border-bottom: none;
  margin: 150px auto 0 auto;

  @media screen and (max-width: 1110px) {
    flex-direction: column;
    gap: 50px;
    padding: 50px 20px;
  }

  .column {
    display: flex;
    flex-direction: column;
    gap: 20px;

    h2 {
      font-size: 1.25rem;
      font-weight: 500;
    }

    .brand {
      display: flex;
      align-items: center;
      gap: 15px;

      img {
        width: 80px;
        height: 80px;
        border-radius: 5px;
      }

      .text {
        display: flex;
        flex-direction: column;
        gap: 5px;

        .brand-name {
          font-size: 1.5em;
          font-weight: 600;
        }

        .brand-text {
          font-size: 1em;
        }

        .swiss-made {
          font-size: 1em;
          margin-block: 5px 0;
          display: flex;
          align-items: center;
          gap: 7px;
          font-weight: 400;

          img {
            width: 15px;
            height: 15px;
            border-radius: 5px;
          }
        }
      }
    }

    .links {
      display: flex;
      flex-direction: column;
      gap: 10px;

      a {
        font-size: 1rem;
        color: #000000;
        text-decoration: none;
        transition: all 100ms linear;

        &:hover {
          text-decoration: underline;
          color: #454ade;
        }
      }

      .social-link {
        display: flex;
        align-items: center;
        gap: 5px;
      }
    }
  }
}
</style>
